[2024-07-03T14:02:55.835+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T14:02:55.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:02:54.067128+00:00 [queued]>
[2024-07-03T14:02:55.879+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:02:54.067128+00:00 [queued]>
[2024-07-03T14:02:55.880+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T14:02:55.896+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_to_postgres> on 2024-07-03 14:02:54.067128+00:00
[2024-07-03T14:02:55.903+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=260) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T14:02:55.904+0000] {standard_task_runner.py:63} INFO - Started process 262 to run task
[2024-07-03T14:02:55.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'copy_csv_to_postgres', 'copy_to_postgres', 'manual__2024-07-03T14:02:54.067128+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/csv_postgres.py', '--cfg-path', '/tmp/tmp5twihyyx']
[2024-07-03T14:02:55.909+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask copy_to_postgres
[2024-07-03T14:02:55.982+0000] {task_command.py:426} INFO - Running <TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:02:54.067128+00:00 [running]> on host 39ccb9f93fc5
[2024-07-03T14:02:56.100+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_csv_to_postgres' AIRFLOW_CTX_TASK_ID='copy_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T14:02:54.067128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-03T14:02:54.067128+00:00'
[2024-07-03T14:02:56.102+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T14:02:56.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T14:02:56.106+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_postgres.py", line 17, in start_pipeline
    load_csv_to_postgres()
  File "/opt/airflow/dags/csv_postgres.py", line 9, in load_csv_to_postgres
    df = pd.read_csv('/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details'
[2024-07-03T14:02:56.122+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=copy_csv_to_postgres, task_id=copy_to_postgres, run_id=manual__2024-07-03T14:02:54.067128+00:00, execution_date=20240703T140254, start_date=20240703T140255, end_date=20240703T140256
[2024-07-03T14:02:56.140+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task copy_to_postgres ([Errno 2] No such file or directory: '/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details'; 262)
[2024-07-03T14:02:56.167+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T14:02:56.198+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:02:56.201+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
