[2024-07-03T18:29:26.659+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T18:29:26.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres.load_csvs_to_postgres manual__2024-07-03T18:29:24.923102+00:00 [queued]>
[2024-07-03T18:29:26.679+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres.load_csvs_to_postgres manual__2024-07-03T18:29:24.923102+00:00 [queued]>
[2024-07-03T18:29:26.679+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-03T18:29:26.691+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csvs_to_postgres> on 2024-07-03 18:29:24.923102+00:00
[2024-07-03T18:29:26.695+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T18:29:26.696+0000] {standard_task_runner.py:63} INFO - Started process 127 to run task
[2024-07-03T18:29:26.698+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres', 'load_csvs_to_postgres', 'manual__2024-07-03T18:29:24.923102+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_postgres.py', '--cfg-path', '/tmp/tmpjyurxhxw']
[2024-07-03T18:29:26.702+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask load_csvs_to_postgres
[2024-07-03T18:29:26.789+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres.load_csvs_to_postgres manual__2024-07-03T18:29:24.923102+00:00 [running]> on host 9dffc1d7579f
[2024-07-03T18:29:26.947+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres' AIRFLOW_CTX_TASK_ID='load_csvs_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T18:29:24.923102+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-03T18:29:24.923102+00:00'
[2024-07-03T18:29:26.949+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T18:29:26.994+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T18:29:26.996+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_to_postgres.py", line 17, in load_csvs_to_postgres
    (f'/meltano/public-employee_territories-{current_date}.csv', 'employee_territories'),
                                             ^^^^^^^^^^^^
NameError: name 'current_date' is not defined
[2024-07-03T18:29:27.025+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres, task_id=load_csvs_to_postgres, run_id=manual__2024-07-03T18:29:24.923102+00:00, execution_date=20240703T182924, start_date=20240703T182926, end_date=20240703T182927
[2024-07-03T18:29:27.059+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 80 for task load_csvs_to_postgres (name 'current_date' is not defined; 127)
[2024-07-03T18:29:27.083+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T18:29:27.125+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T18:29:27.130+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
