[2024-07-03 17:11:11 -0300] [181458] [INFO] Starting gunicorn 21.2.0
[2024-07-03 17:11:11 -0300] [181458] [ERROR] Connection in use: ('::', 8793)
[2024-07-03 17:11:11 -0300] [181458] [ERROR] Retrying in 1 second.
[2024-07-03 17:11:12 -0300] [181458] [ERROR] Connection in use: ('::', 8793)
[2024-07-03 17:11:12 -0300] [181458] [ERROR] Retrying in 1 second.
[2024-07-03 17:11:13 -0300] [181458] [ERROR] Connection in use: ('::', 8793)
[2024-07-03 17:11:13 -0300] [181458] [ERROR] Retrying in 1 second.
[2024-07-03 17:11:14 -0300] [181458] [ERROR] Connection in use: ('::', 8793)
[2024-07-03 17:11:14 -0300] [181458] [ERROR] Retrying in 1 second.
[2024-07-03 17:11:15 -0300] [181458] [ERROR] Connection in use: ('::', 8793)
[2024-07-03 17:11:15 -0300] [181458] [ERROR] Retrying in 1 second.
[2024-07-03 17:11:16 -0300] [181458] [ERROR] Can't connect to ('::', 8793)
[2m2024-07-03T20:11:17.498379Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:11:49.596441Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:12:29.318722Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:13:01.245697Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:13:33.584223Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:14:06.123783Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:14:37.901643Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:15:09.932270Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:15:41.892069Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:16:13.794333Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:16:46.491638Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:17:18.562380Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:17:50.541212Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:18:22.435513Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:18:54.322754Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:19:26.215653Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:19:58.113708Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:20:29.998206Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:21:07.412250Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:21:39.749385Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:22:12.809664Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:22:45.578307Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:23:17.587530Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:23:49.609457Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:24:21.719921Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:24:53.759529Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:25:25.666382Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:25:57.597646Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:26:30.405526Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:27:06.114077Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:27:38.414022Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:28:10.409061Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:28:42.708368Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:29:15.218111Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:29:47.367700Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:30:19.530193Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:30:51.540048Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:31:23.501447Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:31:57.063105Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:32:29.293201Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:33:15.519255Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:33:47.448023Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:34:22.701209Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:34:54.640197Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:35:28.886052Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:36:00.713337Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:36:34.393698Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:37:07.139963Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:37:39.393135Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:38:11.587992Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:38:43.529929Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:39:15.308260Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:39:47.356516Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:40:19.443971Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:40:51.461918Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:41:23.623121Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:41:56.530905Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:42:28.595291Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:43:07.614615Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:43:39.935290Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:44:12.576106Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:44:44.861894Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:45:16.914823Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2024-07-03T20:45:48.773765Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
Process ForkProcess-2:
Traceback (most recent call last):
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gabriela/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/gabriela/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/dag_processing/manager.py", line 240, in _run_processor_manager
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/dag_processing/manager.py", line 475, in start
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/dag_processing/manager.py", line 602, in _run_parsing_loop
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/models/dagwarning.py", line 81, in purge_inactive_dag_warnings
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/retries.py", line 91, in wrapped_function
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
  File "/home/gabriela/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/gabriela/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/retries.py", line 100, in wrapped_function
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/models/dagwarning.py", line 94, in _purge_inactive_dag_warnings_with_retry
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/job.py", line 393, in run_job
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/job.py", line 422, in execute_job
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/scheduler_job_runner.py", line 855, in _execute
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/scheduler_job_runner.py", line 987, in _run_scheduler_loop
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/scheduler_job_runner.py", line 1061, in _do_scheduling
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/retries.py", line 91, in wrapped_function
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
  File "/home/gabriela/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/gabriela/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/retries.py", line 100, in wrapped_function
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/scheduler_job_runner.py", line 1127, in _create_dagruns_for_dags
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/models/dag.py", line 3742, in dags_needing_dagruns
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/daemon_utils.py", line 81, in run_command_with_daemon_option
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 70, in <lambda>
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 52, in _run_scheduler_job
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/job.py", line 395, in run_job
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/job.py", line 240, in complete_execution
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/jobs/job.py", line 332, in _update_in_db
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2853, in get
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 412, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/bin/airflow", line 8, in <module>
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/__main__.py", line 57, in main
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 114, in wrapper
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 67, in scheduler
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/airflow/cli/commands/daemon_utils.py", line 81, in run_command_with_daemon_option
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/daemon/daemon.py", line 397, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/daemon/daemon.py", line 391, in close
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/lockfile/__init__.py", line 204, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/lockfile/pidlockfile.py", line 103, in release
lockfile.NotLocked: /home/gabriela/Documents/meltano-lighthouse/fonte-csv/orchestrate/airflow/airflow-scheduler.pid is not locked
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/daemon/daemon.py", line 391, in close
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/lockfile/__init__.py", line 204, in __exit__
  File "/home/gabriela/Documents/meltano-lighthouse/fonte-csv/.meltano/utilities/airflow/venv/lib/python3.9/site-packages/lockfile/pidlockfile.py", line 103, in release
lockfile.NotLocked: /home/gabriela/Documents/meltano-lighthouse/fonte-csv/orchestrate/airflow/airflow-scheduler.pid is not locked
