[2024-07-03T14:12:30.239+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T14:12:30.262+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:07:25.269453+00:00 [queued]>
[2024-07-03T14:12:30.268+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:07:25.269453+00:00 [queued]>
[2024-07-03T14:12:30.269+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T14:12:30.279+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_to_postgres> on 2024-07-03 14:07:25.269453+00:00
[2024-07-03T14:12:30.285+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=410) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T14:12:30.286+0000] {standard_task_runner.py:63} INFO - Started process 412 to run task
[2024-07-03T14:12:30.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'copy_csv_to_postgres', 'copy_to_postgres', 'manual__2024-07-03T14:07:25.269453+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/csv_postgres.py', '--cfg-path', '/tmp/tmpwfzafki6']
[2024-07-03T14:12:30.289+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask copy_to_postgres
[2024-07-03T14:12:30.353+0000] {task_command.py:426} INFO - Running <TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:07:25.269453+00:00 [running]> on host 39ccb9f93fc5
[2024-07-03T14:12:30.533+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_csv_to_postgres' AIRFLOW_CTX_TASK_ID='copy_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T14:07:25.269453+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-03T14:07:25.269453+00:00'
[2024-07-03T14:12:30.535+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T14:12:30.544+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T14:12:30.549+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_postgres.py", line 18, in start_pipeline
    load_csv_to_postgres()
  File "/opt/airflow/dags/csv_postgres.py", line 10, in load_csv_to_postgres
    df = pd.read_csv('/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details.csv'
[2024-07-03T14:12:30.565+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=copy_csv_to_postgres, task_id=copy_to_postgres, run_id=manual__2024-07-03T14:07:25.269453+00:00, execution_date=20240703T140725, start_date=20240703T141230, end_date=20240703T141230
[2024-07-03T14:12:30.581+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task copy_to_postgres ([Errno 2] No such file or directory: '/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details.csv'; 412)
[2024-07-03T14:12:30.590+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T14:12:30.608+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:12:30.611+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
