[2024-07-03T20:29:01.839+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T20:29:01.865+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres.load_csvs_to_postgres scheduled__2024-07-03T20:28:00+00:00 [queued]>
[2024-07-03T20:29:01.877+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres.load_csvs_to_postgres scheduled__2024-07-03T20:28:00+00:00 [queued]>
[2024-07-03T20:29:01.878+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-03T20:29:01.897+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csvs_to_postgres> on 2024-07-03 20:28:00+00:00
[2024-07-03T20:29:01.905+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=55) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T20:29:01.907+0000] {standard_task_runner.py:63} INFO - Started process 57 to run task
[2024-07-03T20:29:01.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres', 'load_csvs_to_postgres', 'scheduled__2024-07-03T20:28:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_postgres.py', '--cfg-path', '/tmp/tmp0p3pe4d6']
[2024-07-03T20:29:01.911+0000] {standard_task_runner.py:91} INFO - Job 92: Subtask load_csvs_to_postgres
[2024-07-03T20:29:01.969+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres.load_csvs_to_postgres scheduled__2024-07-03T20:28:00+00:00 [running]> on host 9dffc1d7579f
[2024-07-03T20:29:02.092+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres' AIRFLOW_CTX_TASK_ID='load_csvs_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T20:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T20:28:00+00:00'
[2024-07-03T20:29:02.094+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T20:29:02.128+0000] {base.py:84} INFO - Using connection ID 'postgres_destino' for task execution.
[2024-07-03T20:29:02.140+0000] {sql.py:487} INFO - Running statement: TRUNCATE TABLE order_details, parameters: None
[2024-07-03T20:29:02.180+0000] {base.py:84} INFO - Using connection ID 'postgres_destino' for task execution.
[2024-07-03T20:29:02.198+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T20:29:02.199+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_to_postgres.py", line 54, in load_csvs_to_postgres
    cursor.copy_expert(f"COPY {table_name} FROM STDIN WITH CSV", csv_buffer)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(5)
CONTEXT:  COPY order_details, line 2156, column quantity: "1996-07-04"

[2024-07-03T20:29:02.213+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres, task_id=load_csvs_to_postgres, run_id=scheduled__2024-07-03T20:28:00+00:00, execution_date=20240703T202800, start_date=20240703T202901, end_date=20240703T202902
[2024-07-03T20:29:02.251+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 92 for task load_csvs_to_postgres (value too long for type character varying(5)
CONTEXT:  COPY order_details, line 2156, column quantity: "1996-07-04"
; 57)
[2024-07-03T20:29:02.294+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T20:29:02.318+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T20:29:02.336+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
