[2024-07-03T20:34:01.226+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T20:34:01.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres.load_csvs_to_postgres scheduled__2024-07-03T20:33:00+00:00 [queued]>
[2024-07-03T20:34:01.268+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres.load_csvs_to_postgres scheduled__2024-07-03T20:33:00+00:00 [queued]>
[2024-07-03T20:34:01.268+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-03T20:34:01.295+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csvs_to_postgres> on 2024-07-03 20:33:00+00:00
[2024-07-03T20:34:01.301+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=142) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T20:34:01.303+0000] {standard_task_runner.py:63} INFO - Started process 144 to run task
[2024-07-03T20:34:01.306+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres', 'load_csvs_to_postgres', 'scheduled__2024-07-03T20:33:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_postgres.py', '--cfg-path', '/tmp/tmpuo6mygnn']
[2024-07-03T20:34:01.310+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask load_csvs_to_postgres
[2024-07-03T20:34:01.382+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres.load_csvs_to_postgres scheduled__2024-07-03T20:33:00+00:00 [running]> on host 9dffc1d7579f
[2024-07-03T20:34:01.546+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres' AIRFLOW_CTX_TASK_ID='load_csvs_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T20:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T20:33:00+00:00'
[2024-07-03T20:34:01.549+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T20:34:01.600+0000] {base.py:84} INFO - Using connection ID 'postgres_destino' for task execution.
[2024-07-03T20:34:01.618+0000] {sql.py:487} INFO - Running statement: TRUNCATE TABLE order_details, parameters: None
[2024-07-03T20:34:01.693+0000] {base.py:84} INFO - Using connection ID 'postgres_destino' for task execution.
[2024-07-03T20:34:01.717+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T20:34:01.719+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_to_postgres.py", line 54, in load_csvs_to_postgres
    cursor.copy_expert(f"COPY {table_name} FROM STDIN WITH CSV", csv_buffer)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(5)
CONTEXT:  COPY order_details, line 2156, column quantity: "1996-07-04"

[2024-07-03T20:34:01.735+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres, task_id=load_csvs_to_postgres, run_id=scheduled__2024-07-03T20:33:00+00:00, execution_date=20240703T203300, start_date=20240703T203401, end_date=20240703T203401
[2024-07-03T20:34:01.757+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task load_csvs_to_postgres (value too long for type character varying(5)
CONTEXT:  COPY order_details, line 2156, column quantity: "1996-07-04"
; 144)
[2024-07-03T20:34:01.771+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T20:34:01.802+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T20:34:01.806+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
