[2024-07-03T14:05:22.671+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T14:05:22.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:05:20.724544+00:00 [queued]>
[2024-07-03T14:05:22.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:05:20.724544+00:00 [queued]>
[2024-07-03T14:05:22.724+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T14:05:22.753+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_to_postgres> on 2024-07-03 14:05:20.724544+00:00
[2024-07-03T14:05:22.765+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=297) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T14:05:22.767+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'copy_csv_to_postgres', 'copy_to_postgres', 'manual__2024-07-03T14:05:20.724544+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/csv_postgres.py', '--cfg-path', '/tmp/tmp49g0fnj6']
[2024-07-03T14:05:22.768+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask copy_to_postgres
[2024-07-03T14:05:22.768+0000] {standard_task_runner.py:63} INFO - Started process 299 to run task
[2024-07-03T14:05:22.852+0000] {task_command.py:426} INFO - Running <TaskInstance: copy_csv_to_postgres.copy_to_postgres manual__2024-07-03T14:05:20.724544+00:00 [running]> on host 39ccb9f93fc5
[2024-07-03T14:05:23.000+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_csv_to_postgres' AIRFLOW_CTX_TASK_ID='copy_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T14:05:20.724544+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-03T14:05:20.724544+00:00'
[2024-07-03T14:05:23.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T14:05:23.004+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T14:05:23.005+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_postgres.py", line 18, in start_pipeline
    load_csv_to_postgres()
  File "/opt/airflow/dags/csv_postgres.py", line 10, in load_csv_to_postgres
    df = pd.read_csv('/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details'
[2024-07-03T14:05:23.063+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=copy_csv_to_postgres, task_id=copy_to_postgres, run_id=manual__2024-07-03T14:05:20.724544+00:00, execution_date=20240703T140520, start_date=20240703T140522, end_date=20240703T140523
[2024-07-03T14:05:23.092+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task copy_to_postgres ([Errno 2] No such file or directory: '/home/gabriela/Documents/Meltano-Projects/lighthouse-project/fonte/order_details'; 299)
[2024-07-03T14:05:23.116+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T14:05:23.147+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:05:23.162+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
